import { Cat } from "@/types/cat";

export const mockData: Cat[] = [
  {
    breeds: [],
    id: "53j",
    url: "https://cdn2.thecatapi.com/images/53j.jpg",
    width: 500,
    height: 385,
  },
  {
    breeds: [],
    id: "80i",
    url: "https://cdn2.thecatapi.com/images/80i.gif",
    width: 450,
    height: 330,
  },
  {
    breeds: [],
    id: "a1b",
    url: "https://cdn2.thecatapi.com/images/a1b.jpg",
    width: 269,
    height: 480,
  },
  {
    breeds: [],
    id: "cgr",
    url: "https://cdn2.thecatapi.com/images/cgr.jpg",
    width: 432,
    height: 650,
  },
  {
    breeds: [],
    id: "djh",
    url: "https://cdn2.thecatapi.com/images/djh.jpg",
    width: 717,
    height: 960,
  },
  {
    breeds: [],
    id: "MTkzNTY5NA",
    url: "https://cdn2.thecatapi.com/images/MTkzNTY5NA.jpg",
    width: 500,
    height: 667,
  },
  {
    breeds: [],
    id: "MjA1MDk2OA",
    url: "https://cdn2.thecatapi.com/images/MjA1MDk2OA.jpg",
    width: 1024,
    height: 702,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 12",
          metric: "3 - 5",
        },
        id: "bure",
        name: "Burmese",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Burmese.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/burmese",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/burmese",
        temperament:
          "Curious, Intelligent, Gentle, Social, Interactive, Playful, Lively",
        origin: "Burma",
        country_codes: "MM",
        country_code: "MM",
        description:
          "Burmese love being with people, playing with them, and keeping them entertained. They crave close physical contact and abhor an empty lap. They will follow their humans from room to room, and sleep in bed with them, preferably under the covers, cuddled as close as possible. At play, they will turn around to see if their human is watching and being entertained by their crazy antics.",
        life_span: "15 - 16",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 4,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Burmese_(cat)",
        hypoallergenic: 1,
        reference_image_id: "4lXnnfxac",
      },
    ],
    id: "4lXnnfxac",
    url: "https://cdn2.thecatapi.com/images/4lXnnfxac.jpg",
    width: 1250,
    height: 650,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 13",
          metric: "4 - 6",
        },
        id: "cymr",
        name: "Cymric",
        vetstreet_url: "http://www.vetstreet.com/cats/cymric",
        temperament: "Gentle, Loyal, Intelligent, Playful",
        origin: "Canada",
        country_codes: "CA",
        country_code: "CA",
        description:
          "The Cymric is a placid, sweet cat. They do not get too upset about anything that happens in their world. They are loving companions and adore people. They are smart and dexterous, capable of using his paws to get into cabinets or to open doors.",
        life_span: "8 - 14",
        indoor: 0,
        lap: 1,
        alt_names: "Spangle",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 5,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 3,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 1,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Cymric_(cat)",
        hypoallergenic: 0,
        reference_image_id: "3dbtapCWM",
      },
    ],
    id: "lF3ZTucYp",
    url: "https://cdn2.thecatapi.com/images/lF3ZTucYp.jpg",
    width: 1280,
    height: 720,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "8 - 20",
          metric: "4 - 9",
        },
        id: "raga",
        name: "Ragamuffin",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Ragamuffin.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/ragamuffin",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/ragamuffin",
        temperament: "Affectionate, Friendly, Gentle, Calm",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "The Ragamuffin is calm, even tempered and gets along well with all family members. Changes in routine generally do not upset her. She is an ideal companion for those in apartments, and with children due to her patient nature.",
        life_span: "12 - 16",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 3,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 3,
        stranger_friendly: 5,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Ragamuffin_cat",
        hypoallergenic: 0,
        reference_image_id: "SMuZx-bFM",
      },
    ],
    id: "mK0P2HlfO",
    url: "https://cdn2.thecatapi.com/images/mK0P2HlfO.jpg",
    width: 1416,
    height: 873,
  },
];
