export const WIDTH = {
  CONTENT_MAX: 1200,
  COLUMN_GAP: 16,
  IMAGE: 200,
  PADDING: 16,
};

export const COLUMN_BREAK_POINT = {
  TWO: 2 * WIDTH.IMAGE + WIDTH.COLUMN_GAP + 2 * WIDTH.PADDING,
  THREE: 3 * WIDTH.IMAGE + 2 * WIDTH.COLUMN_GAP + 2 * WIDTH.PADDING,
};
